
import pytest

from helpers import remove_tree, short_temporary_directory

from ecobuild import _cppbuild
from ecobuild.config import ModuleConfig
from ecobuild.errors import EcoBuildError, ErrorCode

pytestmark = pytest.mark.cppbuild


@pytest.fixture(scope="module")
def module_root():
    # Windowsのパス長の制限を避けるため、短い一時ディレクトリを使う。
    base = short_temporary_directory()
    root = base / "Calc"
    root.mkdir()
    _cppbuild.create_module_solution(root, "Calc", ModuleConfig.for_new_module("Calc", app=True).projects)
    _cppbuild.update(root)
    yield root
    remove_tree(base)


def test_layout_and_templates(module_root):
    assert (module_root / "CMakeLists.txt").read_text(encoding="utf-8").startswith("# Generated by CppBuild")
    assert (module_root / "Calc/include/Calc/Calc.h").read_text(encoding="utf-8").startswith("#pragma once")
    assert '#include "Calc/Calc.h"' in (module_root / "Calc/src/Calc.cpp").read_text(encoding="utf-8")
    assert "TEST(Calc, Builds)" in (module_root / "CalcTest/src/CalcTest.cpp").read_text(encoding="utf-8")
    templates = _cppbuild.open_solution(module_root).settings.get().file_templates
    assert set(templates) == set(_cppbuild.TEMPLATES)
    assert not list(module_root.glob(".ecobuild-template-*"))


def test_build_test_run(module_root):
    assert _cppbuild.build(module_root, project=None, configuration="Debug").success
    outcome = _cppbuild.test(module_root, project=None, configuration="Debug")
    assert [c.status for c in outcome.cases] == ["passed"]
    assert _cppbuild.run(module_root, project=None, configuration="Debug", arguments="").success


def test_project_at(module_root):
    assert _cppbuild.project_at(module_root, module_root / "CalcTest" / "src") == "CalcTest"
    assert _cppbuild.project_at(module_root, module_root) is None


def test_build_failure_is_reported(module_root):
    source = module_root / "Calc/src/Calc.cpp"
    original = source.read_text(encoding="utf-8")
    source.write_text(original + "this is not C++;\n", encoding="utf-8")
    try:
        with pytest.raises(EcoBuildError) as error:
            _cppbuild.build(module_root, project="Calc", configuration="Debug")
        assert error.value.code == ErrorCode.BUILD_FAILED
    finally:
        source.write_text(original, encoding="utf-8")



def test_unknown_project_and_configuration(module_root):
    with pytest.raises(EcoBuildError) as error:
        _cppbuild.build(module_root, project="Nope", configuration="Debug")
    assert error.value.code == ErrorCode.PROJECT_NOT_FOUND and "CalcTest" in error.value.hint
    with pytest.raises(EcoBuildError) as error:
        _cppbuild.build(module_root, project=None, configuration="Foo")
    assert error.value.code == ErrorCode.INVALID_CONFIGURATION


def test_run_failure_reports_exit_code(module_root):
    """プログラムが0以外で終わったら、終了コードとプログラムの出力だけを返す（ビルドの出力は含めない）。"""
    main = module_root / "CalcApp/src/main.cpp"
    original = main.read_text(encoding="utf-8")
    main.write_text('#include <cstdio>\nint main() { std::puts("bye"); return 3; }\n', encoding="utf-8")
    try:
        with pytest.raises(EcoBuildError) as error:
            _cppbuild.run(module_root, project=None, configuration="Debug", arguments="")
        assert error.value.code == ErrorCode.RUN_FAILED and "終了コード 3" in error.value.message
        assert error.value.details["returncode"] == 3 and error.value.details["output"].strip() == "bye"
    finally:
        main.write_text(original, encoding="utf-8")


def test_generated_file_classification():
    assert _cppbuild.is_generated_or_managed("CMakeLists.txt")
    assert _cppbuild.is_generated_or_managed("Calc/CMakeLists.txt")
    assert _cppbuild.is_generated_or_managed(".cppbuild/project.json")
    assert not _cppbuild.is_generated_or_managed(".cppbuild/output/intermediate/x")
    assert not _cppbuild.is_generated_or_managed("deps/STL/CMakeLists.txt")
    assert not _cppbuild.is_generated_or_managed("Calc/src/Calc.cpp")
