import shutil
import tempfile
from pathlib import Path

import pytest

from ecobuild import _cppbuild
from ecobuild.config import ModuleConfig
from ecobuild.errors import EcoBuildError, ErrorCode

pytestmark = pytest.mark.cppbuild


@pytest.fixture(scope="module")
def module_root():
    # Windowsのパス長の制限を避けるため、短い一時ディレクトリを使う。
    base = Path(tempfile.mkdtemp(prefix="eb"))
    root = base / "Calc"
    root.mkdir()
    _cppbuild.create_module_solution(root, "Calc", ModuleConfig.for_new_module("Calc", app=True).projects)
    _cppbuild.update(root)
    yield root
    shutil.rmtree(base, ignore_errors=True)


def test_layout_and_templates(module_root):
    assert (module_root / "CMakeLists.txt").read_text(encoding="utf-8").startswith("# Generated by CppBuild")
    assert (module_root / "Calc/include/Calc/Calc.h").read_text(encoding="utf-8").startswith("#pragma once")
    assert '#include "Calc/Calc.h"' in (module_root / "Calc/src/Calc.cpp").read_text(encoding="utf-8")
    assert "TEST(Calc, Builds)" in (module_root / "CalcTest/src/CalcTest.cpp").read_text(encoding="utf-8")
    templates = _cppbuild.open_solution(module_root).settings.get().file_templates
    assert set(templates) == set(_cppbuild.TEMPLATES)
    assert not list(module_root.glob(".ecobuild-template-*"))


def test_build_test_run(module_root):
    assert _cppbuild.build(module_root, project=None, configuration="Debug").success
    outcome = _cppbuild.test(module_root, project=None, configuration="Debug")
    assert [c.status for c in outcome.cases] == ["passed"]
    assert _cppbuild.run(module_root, project=None, configuration="Debug", arguments="").success


def test_project_at(module_root):
    assert _cppbuild.project_at(module_root, module_root / "CalcTest" / "src") == "CalcTest"
    assert _cppbuild.project_at(module_root, module_root) is None


def test_build_failure_is_reported(module_root):
    source = module_root / "Calc/src/Calc.cpp"
    original = source.read_text(encoding="utf-8")
    source.write_text(original + "this is not C++;\n", encoding="utf-8")
    try:
        with pytest.raises(EcoBuildError) as error:
            _cppbuild.build(module_root, project="Calc", configuration="Debug")
        assert error.value.code == ErrorCode.BUILD_FAILED
    finally:
        source.write_text(original, encoding="utf-8")


def test_generated_file_classification():
    assert _cppbuild.is_generated_or_managed("CMakeLists.txt")
    assert _cppbuild.is_generated_or_managed("Calc/CMakeLists.txt")
    assert _cppbuild.is_generated_or_managed(".cppbuild/project.json")
    assert not _cppbuild.is_generated_or_managed(".cppbuild/output/intermediate/x")
    assert not _cppbuild.is_generated_or_managed("deps/STL/CMakeLists.txt")
    assert not _cppbuild.is_generated_or_managed("Calc/src/Calc.cpp")
